### ISSUE TITLE
incompatibility?

### ISSUE THREAD

**Issue by ali-ballout** [sybrenjansen/mpire#82] opened 2023-07-16 00:26 UTC
Hello, I had tried to use this with the package owlready2 to be able to share the ontology object which is a complex object with multiple processes. But sadly I wasnt even able to try it. the code was silently crashing. After some tinkering I found out that if I use any of owlready2 components objects/methods after importing mpire the code just silenly stops as if I didnt even run it.

**Comment by sybrenjansen** [comment] 2023-07-18 08:25
This works fine on my end:

```
from mpire import WorkerPool
from owlready2 import get_ontology

onto = get_ontology("http://www.lesfleursdunormal.fr/static/_downloads/pizza_onto.owl")
onto.load()

def job(shared_onto, idx):
    return str(list(shared_onto.classes())[idx])

with WorkerPool(2, shared_objects=onto) as pool:
    print(pool.map(job, range(6)))
```

This prints the first 6 classes in the ontology. Sharing the ontology when using `fork` works as expected. However, I noticed that if I change the `job` function to:

```
def job(shared_onto, idx):
    return list(shared_onto.classes())[idx]
```

which returns the class instead of the string representation, I get the following error:

```
_pickle.PicklingError: Can't pickle pizza_onto.Pizza: attribute lookup Pizza on owlready2.entity failed
```

It seems the package you're using hasn't implemented pickling. So if you're not using fork as start method (e.g., you're on Windows), then it will crash like this. But it should give the error message though.

**Comment by ali-ballout** [comment] 2023-07-18 15:15
Yes in my case I am on windows, but it didnt even get there. As soon as the imports happen it simply dies. In anycase  thank you so much. Btw it is very interesting that you are able to share or send the parent object (ontology) and lookup a class object in it but are not able to send it back. The idea is that you already did the communication of the complex class one way why cant it be done the other way.

**Comment by sybrenjansen** [comment] 2023-07-19 07:54
This works only on Unix based systems where `fork` is available. My example of sharing the ontology object won't work on Windows I'm afraid.

The nice thing about `fork` is that when you create a new child process you don't need to make a copy of an object, so there's no serialization (pickling) involved. However, this is only true when I create a child process. Once I need to pass an object from one existing process to another then serialization is needed and it throws the error.

On Windows `fork` is not available and would require serialization. I'm not sure whether the silently dying interpreter comes from Windows that has trouble handling this or whether it's actually mpire.

**Comment by ali-ballout** [comment] 2023-07-19 13:56
first of all thank you very much for taking the time to tell me this info, I really appreciate it. Second I dont know exactly what is causing the issue but I can tell you it is happening before any invocation of the multiprocessing happens. so no attempt to fork/spawn new processing is going on simply importing mpire .

anyway the best fix is as usual the most popular one, dont use windows your life will be much easier.

**Comment by sybrenjansen** [comment] 2023-07-19 14:15
I didn't realize it was already crashing on import. That's very strange. There's not a lot of interesting things happening on import...

And does it also crash on import if you haven't used `owlready2`?

**Comment by ali-ballout** [comment] 2023-07-19 14:34
No, only when both are included, Ive tried having them in the same module or in different ones imported to the same common module. when ever they are together the code dies. what happens is about 1 to 2 seconds after the import happens the process silently dies. Lets say something like this:

`import owlready2
import mpire

print('hello')
sleep(1)
print('done')`

I just get as output "hello" and then just nothing.

**Comment by ali-ballout** [comment] 2023-07-19 17:00
After investigating more, it happens only when loading some(note all) ontologies using owlready2.get_ontology() if mpire is imported, which might mean some ontology might require a certain module to run in owlready2 which would then conflict with mpire. Thats the most I am able to figure out.

**Comment by sybrenjansen** [comment] 2023-07-21 07:45
Have you looked at `freeze_support`? See: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support.

This might be the cause. Try adding that line as the first line in the `if __name__ == '__main__'` block

**Comment by ali-ballout** [comment] 2023-07-22 01:35
will test this later for now I have gone another route by using objects that can be pickled

**Comment by sybrenjansen** [comment] 2023-08-22 08:37
Closing this issue for now. You can repopen it when the issue arises again

**Closed by sybrenjansen** 2023-08-22 08:37 UTC
