### ISSUE TITLE
mpire-dashboard command doesn't open dashboard on windows

### ISSUE THREAD

**Issue by fuubarbaz** [sybrenjansen/mpire#99] opened 2023-10-18 09:16 UTC
I'm running 2.8.0 version. While running mpire-dashboard command on powershell, it asks me to choose the application, after selecting chrome or mozilla it shows me the script itself instead of dasboard.
Am I doing something wrong ? 

![image](https://github.com/sybrenjansen/mpire/assets/76524463/8da2e32d-6852-40e1-805f-fb21b30712fd)

**Comment by sybrenjansen** [comment] 2023-10-18 09:52
If you run this in powershell it should automatically choose Python to run it, looking at the first line of the file. What is the command that you're using on powershell to run it?

After it's started, it will tell you that `MPIRE dashboad started on http://localhost:<PORT>`. You can then go to that URL to see the actual dashboard.

**Comment by fuubarbaz** [comment] 2023-10-18 09:55
> If you run this in powershell it should automatically choose Python to run it, looking at the first line of the file. What is the command that you're using on powershell to run it?
>  I'm using  command mpire-dashboard.

**Comment by sybrenjansen** [comment] 2024-01-08 19:09
I can confirm I have the same issue on Windows. Will look into it shortly

**Comment by sybrenjansen** [comment] 2024-01-08 21:05
I tried to find a solution to this, but couldn't get it to work. The shebang line at the start of the script is not picked up by my conda installation, or requires something I'm not aware off. 

I will document it as not supported for Windows right now and close the ticket. The reason for closing is because you can create your own script quite easily by simply importing `start_dashboard` from `mpire.dashboard` and then calling that function yourself. 

If you do manage to get it to work then please submit a PR :)

**Closed by sybrenjansen** 2024-01-08 21:05 UTC
Labels: bug
